### ISSUE TITLE
pointing to a bad specific direction

### ISSUE THREAD

**Issue by gtuxyco** [wp-orbis/wp-orbis#14]
This line use a pronamic url and produce redirecting pronamic domain
https://github.com/wp-orbis/wp-orbis/blob/develop/includes/projects.php#L390

**Comment by remcotolsma** [comment]
Sorry for the late reply, just removed this in https://github.com/wp-orbis/wp-orbis/commit/163d02bee3462ade5818823d92f8f447365e09d4.
