### ISSUE TITLE
Duplication of Dashboard line at top of main page

### ISSUE THREAD

**Issue by weisner** [wp-orbis/wp-orbis#9]
I hope the image makes clear what I am meaning as I am not sure I can explain it better.

![orbisdashboard](https://cloud.githubusercontent.com/assets/5287624/5742903/4daea5c6-9bca-11e4-8a28-914655263703.JPG)

Although not harmful to the function of the site it is less than satisfactory. I will be experimenting to resolve it, and report my findings. However if anyone here has an answer I would be grateful to have it.

**Comment by kjtolsma** [comment]
Are you using the latest version of the Orbis theme https://github.com/wp-orbis/wt-orbis. I can remember i fixed this bug. It had to do with a while loop that shouldn't be there. I fixed it in this commit: https://github.com/wp-orbis/wt-orbis/commit/bedf20cdb62cf8a71ba42ffeb1d0d6f6b284cddb.

**Comment by weisner** [comment]
KJTOLSMA
Thank you, I think you may be right. I will check the theme and be sure that it is most current.

**Comment by weisner** [comment]
KJTOLSMA, Thank you.
This resolved the issue, I was not aware of the theme update being available and was looking to find the code block(s) and contribute my changes as a work around. You have saved me much time.
